### PR TITLE
Change font to Roboto Mono

### PR DESCRIPTION
**Pull request by abhcs**
Fix #215 in [policyengine-app](https://github.com/PolicyEngine/policyengine-app).

Used the information in https://discuss.streamlit.io/t/how-to-change-font-globally/23738/4.

### CODE REVIEW

**Comment by anth-volk** [comment]
Alas, I don't have write access on this repo! @nikhilwoodruff, could you review? Thanks so much for this, @abhcs.

**Comment by anth-volk** [comment]
I actually can work on this now. @abhcs, would you mind running locally and providing a screenshot of the Python code now?

**Comment by abhcs** [comment]
Use `streamlit run app.py` to view the output.

Before change:
Screenshot 2023-12-21 at 6 15 10 PM

After change:
Screenshot 2023-12-21 at 6 18 11 PM

**Comment by anth-volk** [comment]
Thanks for the screenshots. Of course, I understand that I could run locally, but since you already have it up and your machine is already configured, we typically ask contributors to share screenshots, especially when working across issues - for example, I don’t personally work with streamlit very much, and thus would have to spend time configuring that you’ve already put in.

Thank you for the contributions, as well. I’ll circle back to these tomorrow during the workday.

**Comment by anth-volk** [comment]
This all looks great, @abhcs, apologies for the delay in reviewing. Thanks for fixing this.

**Pull request merged**
